import {MainBottomTabParamList} from './mainBottomTabParams';
import {AccountStackParams} from './authStackParamList';
import {BottomTabNavigationProp} from '@react-navigation/bottom-tabs';
import {NativeStackNavigationProp} from '@react-navigation/native-stack';
import {useNavigation, CompositeNavigationProp} from '@react-navigation/native';
export type {MainBottomTabParamList};
export type {AccountStackParams};
export type {BottomTabNavigationProp};
export type {NativeStackNavigationProp};
export type {CompositeNavigationProp};
export {useNavigation};
